apiVersion: v2
name: pagopareceiptpdfgenerator
description: Microservice description
type: application
version: 0.189.0
appVersion: 1.16.2-1-PAGOPA-3396-fix-for-cart-notify
dependencies:
  - name: microservice-chart
    version: 8.0.2
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    alias: pagopa-receipt-pdf-generator
  - name: microservice-chart
    version: 8.0.2
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    alias: pagopa-receipt-pdf-generator-cart
