apiVersion: v2
name: pagopareceiptpdfgenerator
description: Microservice description
type: application
version: 0.191.0
appVersion: 1.16.3-1-PAGOPA-3449-move-helpdesk-regenerate-pdf-in-generator
dependencies:
  - name: microservice-chart
    version: 8.0.2
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    alias: pagopa-receipt-pdf-generator
  - name: microservice-chart
    version: 8.0.2
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    alias: pagopa-receipt-pdf-generator-cart
