apiVersion: v2
name: pagopareceiptpdfgenerator
description: Microservice description
type: application
version: 0.179.0
appVersion: 1.14.11-4-PAGOPA-3364-cart-receipt-generator-function
dependencies:
  - name: microservice-chart
    version: 8.0.2
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    alias: pagopa-receipt-pdf-generator
  - name: microservice-chart
    version: 7.5.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    alias: pagopa-receipt-pdf-generator-cart
