apiVersion: v2
name: pagopareceiptpdfgenerator
description: Microservice description
type: application
version: 0.176.0
appVersion: 1.14.11-1-PAGOPA-3364-cart-receipt-generator-function
dependencies:
  - name: microservice-chart
    version: 8.0.2
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
