apiVersion: v2
name: pagopareceiptpdfgenerator
description: Microservice description
type: application
version: 0.198.0
appVersion: 1.17.1-1-PAGOPA-3464
dependencies:
  - name: microservice-chart
    version: 8.0.2
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    alias: pagopa-receipt-pdf-generator
  - name: microservice-chart
    version: 8.0.2
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    alias: pagopa-receipt-pdf-generator-cart
  - name: microservice-chart
    version: 8.0.2
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    alias: pagopa-receipt-pdf-generator-helpdesk
