apiVersion: v2
name: pagopareceiptpdfgenerator
description: Microservice description
type: application
version: 0.181.0
appVersion: 1.15.0-1-PAGOPA-3370-double-deployment
dependencies:
  - name: microservice-chart
    version: 8.0.2
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    alias: pagopa-receipt-pdf-generator
  - name: microservice-chart
    version: 8.0.2
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    alias: pagopa-receipt-pdf-generator-cart
