apiVersion: v2
name: pagopareceiptpdfgenerator
description: Microservice description
type: application
version: 0.182.0
appVersion: 1.16.0-1-improve-pdf-engine-client
dependencies:
  - name: microservice-chart
    version: 8.0.2
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
